In [1]:
import numpy as np

In [13]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("3rd element from 2nd row:",arr[1,3])

3rd element from 2nd row: 90


In [14]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("3rd element from 2nd row:",arr[0,3])

3rd element from 2nd row: 40


In [15]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("3rd element from 2nd row:",arr[1,0])

3rd element from 2nd row: 60


In [16]:
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("3rd element from 2nd row:",arr[1,0])
print("3rd element from 2nd row:",arr[0,3])
print("the sum of both is:",arr[1,0]+arr[0,3])

3rd element from 2nd row: 60
3rd element from 2nd row: 40
the sum of both is: 100


In [27]:
arr=np.array([[[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]]])
print(arr[0,1,2])
print(arr[0,1,3])
print(arr[0,1,4])
print(arr[0,1,1])
print(arr[0,2,2])
print(arr[0,0,0])

80
90
100
70
130
10


In [31]:
arr=np.array([[[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]]])
print(arr[0,2,1])

120


In [33]:
arr=np.array([[10,20,30,40,50]])
print("array size:",arr.size)
print("shape:",arr.shape)

array size: 5
shape: (1, 5)


In [34]:
a=np.array([[1,2],[3,4],[5,6]])
print("printingthe original array..")
print(a)
a=a.reshape(2,3)
print("printing the reshaped array..")
print(a)

printingthe original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


In [35]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[0,1])
print(a[2,0])

2
5


In [38]:
a=np.linspace(2,20,20)
print(a)

[ 2.          2.94736842  3.89473684  4.84210526  5.78947368  6.73684211
  7.68421053  8.63157895  9.57894737 10.52631579 11.47368421 12.42105263
 13.36842105 14.31578947 15.26315789 16.21052632 17.15789474 18.10526316
 19.05263158 20.        ]


In [39]:
a=np.linspace(2,33,20)
print(a)

[ 2.          3.63157895  5.26315789  6.89473684  8.52631579 10.15789474
 11.78947368 13.42105263 15.05263158 16.68421053 18.31578947 19.94736842
 21.57894737 23.21052632 24.84210526 26.47368421 28.10526316 29.73684211
 31.36842105 33.        ]


In [40]:
arr=np.array([[10,20,30,40,50]])
print("the array:",arr)
print("the maximum value is:",arr.max())
print("the minimum value is:",arr.min())
print("the total sun of the values is:",arr.sum())

the array: [[10 20 30 40 50]]
the maximum value is: 50
the minimum value is: 10
the total sun of the values is: 150


In [41]:
a=np.array([[1,2,20],[10,15,4]])
print("the array is :",a)
print("the maximum elements of columns:",a.max(axis=0))
print("the minimum elements of columns:",a.min(axis=1))
print("the sum elements of columns:",a.sum(axis=1))

the array is : [[ 1  2 20]
 [10 15  4]]
the maximum elements of columns: [10 15 20]
the minimum elements of columns: [1 4]
the sum elements of columns: [23 29]


In [4]:
a=np.array([[1,2,20],[10,15,4]])
print("sqrt of the array",np.sqrt(a))
print("standard deviation of the array",np.std(a))

sqrt of the array [[1.         1.41421356 4.47213595]
 [3.16227766 3.87298335 2.        ]]
standard deviation of the array 7.01585505994973


In [5]:
a=np.array([[1,2,20],[10,15,4]])
b=np.array([[1,4,22],[11,14,5]])
print("the addition of the arrays is:\n",a+b)
print("the subtraction of the arrays is:\n",a-b)
print("the multiplication of the arrays is:\n",a*b)
print("the division of the arrays is:\n",a/b)

the addition of the arrays is:
 [[ 2  6 42]
 [21 29  9]]
the subtraction of the arrays is:
 [[ 0 -2 -2]
 [-1  1 -1]]
the multiplication of the arrays is:
 [[  1   8 440]
 [110 210  20]]
the division of the arrays is:
 [[1.         0.5        0.90909091]
 [0.90909091 1.07142857 0.8       ]]


In [6]:
a=np.array([[1,2,20],[10,15,4]])
b=np.array([[1,4,22],[11,14,5]])
print("arrays vertically concatenated\n",np.vstack((a,b)))
print("arrays vertically concatenated\n",np.hstack((a,b)))

arrays vertically concatenated
 [[ 1  2 20]
 [10 15  4]
 [ 1  4 22]
 [11 14  5]]
arrays vertically concatenated
 [[ 1  2 20  1  4 22]
 [10 15  4 11 14  5]]


In [13]:
arr=np.arange(0,10,2,float)
print(arr)

[0. 2. 4. 6. 8.]


In [14]:
arr=np.linspace(10,20,5)
print("the array over the given range is",arr)

the array over the given range is [10.  12.5 15.  17.5 20. ]


In [15]:
arr=np.linspace(15,28,8)
print("the array over the given range is",arr)

the array over the given range is [15.         16.85714286 18.71428571 20.57142857 22.42857143 24.28571429
 26.14285714 28.        ]


In [17]:
arr=np.linspace(15,28,8,endpoint=False)
print("the array over the given range is",arr)

the array over the given range is [15.    16.625 18.25  19.875 21.5   23.125 24.75  26.375]


In [18]:
arr=np.logspace(10,20,num=5,endpoint=True)
print("the array over the given range is",arr)

the array over the given range is [1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


In [23]:
arr=np.logspace(10,20,num=5,base=2,endpoint=True)
print("the array over the given range is",arr)

the array over the given range is [1.02400000e+03 5.79261875e+03 3.27680000e+04 1.85363800e+05
 1.04857600e+06]


In [6]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([5,6,7,8,9,3,2])
c=a*b;
print(c)

[ 5 12 21 32 45 18 14]


In [9]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([2,3])
print("\nprinting the A array:")
print(a)
print("\nprinting the B array:")
print(b)
print("\nprinting the added array:")
c=a+b;
print(c)


printing the A array:
[[1 2]
 [3 4]
 [5 6]]

printing the B array:
[2 3]

printing the added array:
[[3 5]
 [5 7]
 [7 9]]


In [10]:
a=np.array([[1,2],[3,4],[5,6]])
print("printing array:")
print(a);
print("iterating over the array:")
for x in np.nditer(a):
    print(x)

printing array:
[[1 2]
 [3 4]
 [5 6]]
iterating over the array:
1
2
3
4
5
6


In [11]:
a=np.array([[1,2],[3,4],[5,6]])
print("printing array:")
print(a);
print("iterating over the array:")
for x in np.nditer(a):
    print(x,end=' ')

printing array:
[[1 2]
 [3 4]
 [5 6]]
iterating over the array:
1 2 3 4 5 6 

In [12]:
a=np.array([[1,2],[3,4],[5,6]])
print("printing array:")
print(a)
print("printing the transpose of the array:")
at=a.T
print(at)
for x in np.nditer(a):
    print(x,end=' ')

printing array:
[[1 2]
 [3 4]
 [5 6]]
printing the transpose of the array:
[[1 3 5]
 [2 4 6]]
1 2 3 4 5 6 

In [20]:
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])

print("\nPrinting the array:\n")

print(a)

print("\nPrinting the transpose of the array:\n") 
at= a.T

print(at)

print("\nIterating over the transposed array\n")

for x in np.nditer(at): 
    print(x, end=' ')

print("\nSorting the transposed array in C-style:\n")

c = at.copy(order = 'C')

print(c)

print("\nIterating over the C-style array:\n") 
for x in np.nditer(c): 
    print(x,end=' ')

d = at.copy(order = 'F')

print(d)

print("Iterating over the F-style array:\n") 
for x in np.nditer(d):
    print(x,end=' ')


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Sorting the transposed array in C-style:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 [[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
Iterating over the F-style array:

1 2 3 4 2 4 5 6 10 20 39 3 

In [22]:
a=10
b=20
print("binary representation of a:",bin(a))
print("binary representation of b:",bin(b))
print("bitwise and of a and b:",np.bitwise_and(a,b))

binary representation of a: 0b1010
binary representation of b: 0b10100
bitwise and of a and b: 0


In [23]:
a=10
b=20
print("binary representation of a:",bin(a))
print("binary representation of b:",bin(b))
print("bitwise and of a or b:",np.bitwise_or(a,b))

binary representation of a: 0b1010
binary representation of b: 0b10100
bitwise and of a or b: 30


In [24]:
a=30
print("binary representation of a:",bin(a))
print("invert number",np.invert(a))

binary representation of a: 0b11110
invert number -31


In [2]:
arr=np.array([0,10,20,30,40,50,120])
print("\nthe sin value of the angle",end=" ")
print(np.sin(arr*np.pi/180))
print("\nthe cos value of the angle",end=" ")
print(np.cos(arr*np.pi/180))
print("\nthe tan value of the angle",end=" ")
print(np.tan(arr*np.pi/180))


the sin value of the angle [0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254 ]

the cos value of the angle [ 1.          0.98480775  0.93969262  0.8660254   0.76604444  0.64278761
 -0.5       ]

the tan value of the angle [ 0.          0.17632698  0.36397023  0.57735027  0.83909963  1.19175359
 -1.73205081]


In [5]:
arr=np.array([0,10,20,30,40,50,120])
print("printing the values of the angles of sin")
sinval=np.sin(arr*np.pi/180)
print(sinval)
print("printing the inverse of sin")
cosec=np.arcsin(sinval)
print(cosec)
print("printing the values of the degree")
print(np.degrees(cosec))

print("printing the values of the angles of cos")
cosval=np.cos(arr*np.pi/180)
print(cosval)
print("printing the inverse of cos")
sec=np.arccos(cosval)
print(sec)
print("printing the values of the degree")
print(np.degrees(sec))

print("printing the values of the angles of tan")
tanval=np.tan(arr*np.pi/180)
print(tanval)
print("printing the inverse of tan")
cot=np.arctan(sinval)
print(cot)
print("printing the values of the degree")
print(np.degrees(cot))

printing the values of the angles of sin
[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254 ]
printing the inverse of sin
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755]
printing the values of the degree
[ 0. 10. 20. 30. 40. 50. 60.]
printing the values of the angles of cos
[ 1.          0.98480775  0.93969262  0.8660254   0.76604444  0.64278761
 -0.5       ]
printing the inverse of cos
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 2.0943951 ]
printing the values of the degree
[  0.  10.  20.  30.  40.  50. 120.]
printing the values of the angles of tan
[ 0.          0.17632698  0.36397023  0.57735027  0.83909963  1.19175359
 -1.73205081]
printing the inverse of tan
[0.         0.17193371 0.3295482  0.46364761 0.57128828 0.65369072
 0.71372438]
printing the values of the degree
[ 0.          9.85107612 18.88172123 26.56505118 32.73240721 37.45371956
 40.89339465]


In [6]:
arr=np.array([12.2233,34.3666,234.4330])
print("printing the original values of the array:",end=" ")
print(arr)
print("array value rounded off to 3 decimals values",np.around(arr,3))
print("array value rounded off to -1 decimals values",np.around(arr,-1))

printing the original values of the array: [ 12.2233  34.3666 234.433 ]
array value rounded off to 3 decimals values [ 12.223  34.367 234.433]
array value rounded off to -1 decimals values [ 10.  30. 230.]


In [7]:
arr=np.array([12.2233,34.3666,234.4330])
print(np.floor(arr))

[ 12.  34. 234.]


In [8]:
arr=np.array([12.2233,34.3666,234.4330])
print(np.ceil(arr))

[ 13.  35. 235.]


In [9]:
a=np.array([[1,2,3],[2,4,5],[10,20,39]])
print("the original array:\n")
print(a)
print("\nthe minimun element among the array:",np.amin(a))
print("\nthe maximum element among the array:",np.amax(a))

print("\nthe minimun element among the array:",np.amin(a,0))
print("\nthe maximum element among the array:",np.amax(a,0))

print("\nthe minimun element among the array:",np.amin(a,1))
print("\nthe maximum element among the array:",np.amax(a,1))

the original array:

[[ 1  2  3]
 [ 2  4  5]
 [10 20 39]]

the minimun element among the array: 1

the maximum element among the array: 39

the minimun element among the array: [1 2 3]

the maximum element among the array: [10 20 39]

the minimun element among the array: [ 1  2 10]

the maximum element among the array: [ 3  5 39]


In [10]:
a=np.array([[1,2,3],[2,4,5],[10,20,39]])
print("original values of the array:\n",a)
print("\nptp value along axis 1:",np.ptp(a,1))
print("\nptp value along axis 0:",np.ptp(a,0))

original values of the array:
 [[ 1  2  3]
 [ 2  4  5]
 [10 20 39]]

ptp value along axis 1: [ 2  3 29]

ptp value along axis 0: [ 9 18 36]


In [11]:
a=np.array([1,2,3])
print("Array:\n",a) 
print("percentile",np.percentile(a,10))

Array:
 [1 2 3]
percentile 1.2


In [12]:
a=np.array([[1,2,3],[2,4,5],[10,20,39]])
print("array:\n",a)
print("\npercentile along axis 1:",np.percentile(a,1))
print("\nercentile along axis 0:",np.percentile(a,0))

array:
 [[ 1  2  3]
 [ 2  4  5]
 [10 20 39]]

percentile along axis 1: 1.08

ercentile along axis 0: 1.0


In [3]:
a=np.array([[1,2,3],[2,4,5],[10,20,39]])
print("array:\n",a)
print("\nmedian of array along axis 0:",np.median(a,0))
print("mean of array along axis 0:",np.mean(a,0))
print("average of array along axis 1:",np.average(a,1))

array:
 [[ 1  2  3]
 [ 2  4  5]
 [10 20 39]]

median of array along axis 0: [2. 4. 5.]
mean of array along axis 0: [ 4.33333333  8.66666667 15.66666667]
average of array along axis 1: [ 2.          3.66666667 23.        ]


In [4]:
a=np.array([[1,2,3],[2,4,5],[10,20,39]])
print("sorting along the columns:")
print(np.sort(a))

sorting along the columns:
[[ 1  2  3]
 [ 2  4  5]
 [10 20 39]]


In [6]:
data_type=np.dtype([("name","S10"),("marks",int)])
arr=np.array([("mukesh",200),("john",251)],dtype=data_type)
print("sorting data by name")
print(np.sort(arr,order="name"))

sorting data by name
[(b'john', 251) (b'mukesh', 200)]


In [7]:
a=np.array([90,23,43,5])
print("Original:\n",a)
sort_ind=np.argsort(a)
print("printing indices of sorted data\n",sort_ind)
sort_a=a[sort_ind]
print("printing sorted array")
for i in sort_ind:
    print(a[i],end=" ")

Original:
 [90 23 43  5]
printing indices of sorted data
 [3 1 2 0]
printing sorted array
5 23 43 90 

In [8]:
a=np.array(["a","b","c","d","e"])
b=np.array([12,233,34,22,44])
ind=np.lexsort((a,b))
print("printing indices of sorted data")
print(ind)
print("using indices to sort array")
for i in ind:
    print(a[i],b[i])

printing indices of sorted data
[0 3 2 4 1]
using indices to sort array
a 12
d 22
c 34
e 44
b 233


In [9]:
a=np.array([12,233,34,22,44])
print("printing original array",b)
print("printing location of the non zero elements")
print(b.nonzero)

printing original array [ 12 233  34  22  44]
printing location of the non zero elements
<built-in method nonzero of numpy.ndarray object at 0x0000020BD660C450>


In [12]:
a=np.array([12,233,34,22,44])
print(np.where(b>12))

(array([1, 2, 3, 4], dtype=int64),)


In [21]:
a=np.array([[1,2,3,2],[2,4,5,33],[10,20,39,12]])
print("original array\n:",a)
print("\nid of array a:",id(a))
b=a
print("\nmaking copy of the array a")
print("\nid of b:",id(b))
b.shape=4,3;
print("\nchanges on  b also reflect to a:")
print(a)

original array
: [[ 1  2  3  2]
 [ 2  4  5 33]
 [10 20 39 12]]

id of array a: 2249881610896

making copy of the array a

id of b: 2249881610896

changes on  b also reflect to a:
[[ 1  2  3]
 [ 2  2  4]
 [ 5 33 10]
 [20 39 12]]


In [22]:
a=np.array([[1,2,3,4],[9,4,5,6],[1,2,4,9]])
print("original\n:",a)
print("\nid of an array a",id(a))
b=a.view()
print("\nid of an b",id(b))
print("\nprinting the view b")
print(b)
b.shape=4,3;
print("\nchanges made to the view b do not reflect a")
print("\noriginal array \n",a)
print("\nview\n",b)

original
: [[1 2 3 4]
 [9 4 5 6]
 [1 2 4 9]]

id of an array a 2249881602256

id of an b 2249881603984

printing the view b
[[1 2 3 4]
 [9 4 5 6]
 [1 2 4 9]]

changes made to the view b do not reflect a

original array 
 [[1 2 3 4]
 [9 4 5 6]
 [1 2 4 9]]

view
 [[1 2 3]
 [4 9 4]
 [5 6 1]
 [2 4 9]]


In [24]:
a=np.array([[1,2,3,4],[9,4,5,6],[1,2,4,9]])
print("original\n:",a)
print("\nid of an array a",id(a))
b=a.copy()
print("\nid of an b",id(b))
print("\nprinting the deep copy b")
print(b)
b.shape=4,3;
print("\nchanges made to the copy b do not reflect a")
print("\noriginal array \n",a)
print("\ncopy\n",b)

original
: [[1 2 3 4]
 [9 4 5 6]
 [1 2 4 9]]

id of an array a 2249873316944

id of an b 2249886322384

printing the deep copy b
[[1 2 3 4]
 [9 4 5 6]
 [1 2 4 9]]

changes made to the copy b do not reflect a

original array 
 [[1 2 3 4]
 [9 4 5 6]
 [1 2 4 9]]

copy
 [[1 2 3]
 [4 9 4]
 [5 6 1]
 [2 4 9]]


In [25]:
import numpy.matlib
print(numpy.matlib.empty((2,3)))

[[4.24399158e-314 8.48798317e-314 8.48798317e-314]
 [1.27319747e-313 4.24399158e-314 1.90979621e-313]]


In [26]:
import numpy.matlib
print(numpy.matlib.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
import numpy.matlib
print(numpy.matlib.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
import numpy.matlib
print(numpy.matlib.eye(n=3,M=3,k=0,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [30]:
import numpy.matlib
print(numpy.matlib.eye(n=3,M=3,k=1,dtype=int))

[[0 1 0]
 [0 0 1]
 [0 0 0]]


In [7]:
a=np.array([[10,201],[60,703]])
b=np.array([[10,20],[60,70]])
dot=np.dot(a,b)
print(dot)

[[12160 14270]
 [42780 50410]]


In [8]:
a=np.array([[10,201],[60,703]])
b=np.array([[10,20],[60,70]])
dot=np.vdot(a,b)
print(dot)

56930


In [9]:
a=np.array([[10,201],[60,703]])
b=np.array([[10,20],[60,70]])
dot=np.inner(a,b)
print(dot)

[[ 4120 14670]
 [14660 52810]]


In [10]:
a=np.array([[10,201],[60,703]])
b=np.array([[10,20],[60,70]])
dot=np.matmul(a,b)
print(dot)

[[12160 14270]
 [42780 50410]]


In [12]:
a=np.array([[2,3],[3,100]])
print(np.linalg.det(a))

191.0


In [13]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[4,2,3],[14,58,6],[8,8,12]])
result=np.multiply(array1,array2)
print(result)

[[  4   4   9]
 [ 56 290  36]
 [ 56  64 108]]


In [14]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[4,2,3],[14,58,6],[8,8,12]])
result=np.matmul(array1,array2)
print(result)

[[ 56 142  51]
 [134 346 114]
 [212 550 177]]


In [15]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[4,2,3],[14,58,6],[8,8,12]])
result=np.dot(array1,array2)
print(result)

[[ 56 142  51]
 [134 346 114]
 [212 550 177]]


In [16]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,33]])
z=np.concatenate((x,y))
print(z)

[[ 1  2]
 [ 3  4]
 [12 33]]


In [17]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,33]])
z=np.concatenate((x,y),axis=0)
print(z)

[[ 1  2]
 [ 3  4]
 [12 33]]


In [19]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,33]])
z=np.concatenate((x,y.T),axis=1)
print(z)

[[ 1  2 12]
 [ 3  4 33]]


In [20]:
x=np.array([[1,2],[3,4]])
y=np.array([[12,33]])
z=np.concatenate((x,y),axis=None)
print(z)

[ 1  2  3  4 12 33]
